### ISSUE TITLE
Re-test MSRP after we have multiple instances

### ISSUE THREAD

**Issue by cnevinc** [mozilla-tw/mango#797]
**Describe the bug**
We have 8 GAE instances by default.
Need to re-test MSRP flow to make sure all APIs are stateless and will work as expected.

**Additional context**
I believe this should not be a problem. But it's better we double-check it again.

**Comment by cnevinc** [comment]
@Daisy-pliu Do you have the time to test this again in this sprint?

**Comment by Daisy-pliu** [comment]
@cnevinc 
verify:✅
version: 16717 nighlty
Test: 
1. MSRP034
2. MSRP Admin Page
