### ISSUE TITLE
Remove JD from product

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/mango#825]
Scope:
1. in product default: top sites 
2. in product default: shopping search

And remote config for above two. 

@Jacklin-ux @joechengla we need updated topsite list and shopping search list accordingly.
https://docs.google.com/spreadsheets/d/1p52CgIdA9PMNGY4X0keLVq21AzNOg_yo2Qk-_ULVAtM/edit?ts=5d410e53#gid=1225379349

**Comment by youwenliang** [comment]
Currently JD.ID is removed from Shopping Search and Shopping Home.

**Comment by proevan** [comment]
@weslyhuang please also confirm the top site JD.ID has also been relaced

**Comment by Daisy-pliu** [comment]
Test version: 16855
Confirmed Jd.ID is removed on Production.
