### ISSUE TITLE
Create Indonesia for MSRP in Firebase

### ISSUE THREAD

**Issue by shsu571** [mozilla-tw/mango#833]
Firebase Production needs to create Indonesia in Firestore
Group: Indonesian users

**Comment by shsu571** [comment]
Check Firebase Database:
Mission daily -> auto create?
Need to create  Group Indonesian

**Comment by chianger** [comment]
Nov-18 is the day we're gonna run 1st campaign so Nov-15 should be the due date.

**Comment by Daisy-pliu** [comment]
Release team created "Indonesia Group" on Firestore and "mission_endpoint" on Remote config.
<img width="1194" alt="Screen Shot 2019-11-13 at 3 12 15 PM" src="https://user-images.githubusercontent.com/44990878/68741375-6ae3e480-0628-11ea-9dc3-ce55faa94523.png">
<img width="1290" alt="Screen Shot 2019-11-13 at 3 15 35 PM" src="https://user-images.githubusercontent.com/44990878/68741398-79ca9700-0628-11ea-8222-831af5fc5f45.png">

**Comment by Daisy-pliu** [comment]
verify:✅
