### ISSUE TITLE
May I have the Viewer permission for FirefoxLitePreview project? 

### ISSUE THREAD

**Issue by niyali** [mozilla-tw/mango#834]
Hi there, 

I would like to have the GCP viewer permission for FirefoxLitePreview project. 
Thank you very much.

**Comment by niyali** [comment]
@cnevinc any objection?
If not, could @Daisy-pliu please grant me the viewer access?

Thank you very much.

**Comment by cnevinc** [comment]
Linear is the SRE so view permission is required

**Comment by Daisy-pliu** [comment]
hey I am going to grant you editor permission on Firebase so that you can upload it.

**Comment by Daisy-pliu** [comment]
Write Permission is granted on Nighlty and Prod Firebase

**Comment by Daisy-pliu** [comment]
verify:✅ permission on Nightly and Prod Firebase.
